# Generated by Django 6.0.4 on 2026-05-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('PP', 'PP')], max_length=3)),
                ('numero_documento', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
