# Generated by Django 6.0.4 on 2026-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='region',
            field=models.CharField(blank=True, default='+57', max_length=10),
        ),
    ]
