# Generated by Django 6.0.4 on 2026-05-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_agendamiento', models.ForeignKey(blank=True, db_column='id_agendamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='appointments.agendamiento')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.RESTRICT, to='patients.paciente')),
            ],
            options={
                'db_table': 'sesion',
            },
        ),
        migrations.CreateModel(
            name='DetalleSesion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicamento')),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='treatments.sesion')),
                ('id_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='treatments.tratamiento')),
            ],
            options={
                'db_table': 'detalle_sesion',
            },
        ),
    ]
