# Generated by Django 6.0.4 on 2026-05-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='id_agendamiento',
            field=models.ForeignKey(blank=True, db_column='id_agendamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='appointments.agendamiento'),
        ),
    ]
