# Generated by Django 6.0.4 on 2026-05-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicamento',
            unique_together={('nombre', 'presentacion', 'unidad_medida')},
        ),
    ]
