# Generated by Django 6.0.4 on 2026-05-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_concentracion_from_presentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentacion',
            old_name='cantidad',
            new_name='concentracion',
        ),
    ]
