# Generated by Django 6.0.4 on 2026-05-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_categoria_medicamento_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
