# Generated by Django 6.0.4 on 2026-05-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
