export const countryOptions = [
  {"value": "1", "label": "🇺🇸🇨🇦 +1 USA / Canadá"},
  {"value": "7", "label": "🇷🇺🇰🇿 +7 Rusia / Kazajistán"},
  {"value": "20", "label": "🇪🇬 +20 Egipto"},
  {"value": "27", "label": "🇿🇦 +27 Sudáfrica"},
  {"value": "30", "label": "🇬🇷 +30 Grecia"},
  {"value": "31", "label": "🇳🇱 +31 Países Bajos"},
  {"value": "32", "label": "🇧🇪 +32 Bélgica"},
  {"value": "33", "label": "🇫🇷 +33 Francia"},
  {"value": "34", "label": "🇪🇸 +34 España"},
  {"value": "36", "label": "🇭🇺 +36 Hungría"},
  {"value": "39", "label": "🇮🇹 +39 Italia"},
  {"value": "40", "label": "🇷🇴 +40 Rumania"},
  {"value": "41", "label": "🇨🇭 +41 Suiza"},
  {"value": "43", "label": "🇦🇹 +43 Austria"},
  {"value": "44", "label": "🇬🇧 +44 Reino Unido"},
  {"value": "45", "label": "🇩🇰 +45 Dinamarca"},
  {"value": "46", "label": "🇸🇪 +46 Suecia"},
  {"value": "47", "label": "🇳🇴 +47 Noruega"},
  {"value": "48", "label": "🇵🇱 +48 Polonia"},
  {"value": "49", "label": "🇩🇪 +49 Alemania"},
  {"value": "51", "label": "🇵🇪 +51 Perú"},
  {"value": "52", "label": "🇲🇽 +52 México"},
  {"value": "53", "label": "🇨🇺 +53 Cuba"},
  {"value": "54", "label": "🇦🇷 +54 Argentina"},
  {"value": "55", "label": "🇧🇷 +55 Brasil"},
  {"value": "56", "label": "🇨🇱 +56 Chile"},
  {"value": "57", "label": "🇨🇴 +57 Colombia"},
  {"value": "58", "label": "🇻🇪 +58 Venezuela"},
  {"value": "60", "label": "🇲🇾 +60 Malasia"},
  {"value": "61", "label": "🇦🇺 +61 Australia"},
  {"value": "62", "label": "🇮🇩 +62 Indonesia"},
  {"value": "63", "label": "🇵🇭 +63 Filipinas"},
  {"value": "64", "label": "🇳🇿 +64 Nueva Zelanda"},
  {"value": "65", "label": "🇸🇬 +65 Singapur"},
  {"value": "66", "label": "🇹🇭 +66 Tailandia"},
  {"value": "81", "label": "🇯🇵 +81 Japón"},
  {"value": "82", "label": "🇰🇷 +82 Corea del Sur"},
  {"value": "84", "label": "🇻🇳 +84 Vietnam"},
  {"value": "86", "label": "🇨🇳 +86 China"},
  {"value": "90", "label": "🇹🇷 +90 Turquía"},
  {"value": "91", "label": "🇮🇳 +91 India"},
  {"value": "92", "label": "🇵🇰 +92 Pakistán"},
  {"value": "93", "label": "🇦🇫 +93 Afganistán"},
  {"value": "94", "label": "🇱🇰 +94 Sri Lanka"},
  {"value": "98", "label": "🇮🇷 +98 Irán"},
  {"value": "212", "label": "🇲🇦 +212 Marruecos"},
  {"value": "351", "label": "🇵🇹 +351 Portugal"},
  {"value": "353", "label": "🇮🇪 +353 Irlanda"},
  {"value": "380", "label": "🇺🇦 +380 Ucrania"},
  {"value": "971", "label": "🇦🇪 +971 Emiratos Árabes"},
  {"value": "972", "label": "🇮🇱 +972 Israel"}
];
